name: 'Deploy'
description: 'Deploy the project to GitHub Pages'

runs:
  using: 'composite'
  steps:
    - name: Create 404 Page
      run: cp packages/frontend/dist/index.html packages/frontend/dist/404.html
      shell: bash
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: packages/frontend/dist
